# Makefile.in generated by automake 1.18.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2025 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
am__rm_f = rm -f $(am__rm_f_notfound)
am__rm_rf = rm -rf $(am__rm_f_notfound)
pkgdatadir = $(datadir)/sugarmaker
pkgincludedir = $(includedir)/sugarmaker
pkglibdir = $(libdir)/sugarmaker
pkglibexecdir = $(libexecdir)/sugarmaker
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = aarch64-unknown-linux-android
host_triplet = aarch64-unknown-linux-android
target_triplet = aarch64-unknown-linux-android
bin_PROGRAMS = sugarmaker$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = cpuminer-config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_sugarmaker_OBJECTS = sugarmaker-cpu-miner.$(OBJEXT) \
	sugarmaker-util.$(OBJEXT) sugarmaker-sha2.$(OBJEXT) \
	yespower-1.0.1/sugarmaker-sha256.$(OBJEXT) \
	yespower-1.0.1/sugarmaker-yespower-opt.$(OBJEXT) \
	sugarmaker-YespowerSugar.$(OBJEXT) \
	sugarmaker-YespowerIso.$(OBJEXT) \
	sugarmaker-YespowerNull.$(OBJEXT) \
	sugarmaker-YespowerUrx.$(OBJEXT) \
	sugarmaker-YespowerLitb.$(OBJEXT) \
	sugarmaker-YespowerIots.$(OBJEXT) \
	sugarmaker-YespowerItc.$(OBJEXT) \
	yespower-1.0.1-power2b/sugarmaker-sha256-p2b.$(OBJEXT) \
	yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.$(OBJEXT) \
	yespower-1.0.1-power2b/sugarmaker-blake2b.$(OBJEXT) \
	sugarmaker-YespowerMbc.$(OBJEXT) \
	sugarmaker-YespowerYtn.$(OBJEXT) \
	sugarmaker-YespowerAdvc.$(OBJEXT)
sugarmaker_OBJECTS = $(am_sugarmaker_OBJECTS)
sugarmaker_DEPENDENCIES =
sugarmaker_LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(sugarmaker_LDFLAGS) \
	$(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/sugarmaker-YespowerAdvc.Po \
	./$(DEPDIR)/sugarmaker-YespowerIots.Po \
	./$(DEPDIR)/sugarmaker-YespowerIso.Po \
	./$(DEPDIR)/sugarmaker-YespowerItc.Po \
	./$(DEPDIR)/sugarmaker-YespowerLitb.Po \
	./$(DEPDIR)/sugarmaker-YespowerMbc.Po \
	./$(DEPDIR)/sugarmaker-YespowerNull.Po \
	./$(DEPDIR)/sugarmaker-YespowerSugar.Po \
	./$(DEPDIR)/sugarmaker-YespowerUrx.Po \
	./$(DEPDIR)/sugarmaker-YespowerYtn.Po \
	./$(DEPDIR)/sugarmaker-cpu-miner.Po \
	./$(DEPDIR)/sugarmaker-sha2.Po ./$(DEPDIR)/sugarmaker-util.Po \
	yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-blake2b.Po \
	yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-sha256-p2b.Po \
	yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-yespower-opt-p2b.Po \
	yespower-1.0.1/$(DEPDIR)/sugarmaker-sha256.Po \
	yespower-1.0.1/$(DEPDIR)/sugarmaker-yespower-opt.Po
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(sugarmaker_SOURCES)
DIST_SOURCES = $(sugarmaker_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
  || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
       $(am__cd) "$$dir" && echo $$files | $(am__xargs_n) 40 $(am__rm_f); }; \
  }
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(dist_man_MANS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir distdir-am dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP) \
	cpuminer-config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
DIST_SUBDIRS = $(SUBDIRS)
am__DIST_COMMON = $(dist_man_MANS) $(srcdir)/Makefile.in \
	$(srcdir)/cpuminer-config.h.in AUTHORS COPYING ChangeLog NEWS \
	README.md compile config.guess config.sub depcomp install-sh \
	missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -700 -exec chmod u+rwx {} ';' \
      ; rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = -9
DIST_TARGETS = dist-gzip
# Exists only to be overridden by the user if desired.
AM_DISTCHECK_DVI_TARGET = dvi
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = \
  find . \( -type f -a \! \
            \( -name .nfs* -o -name .smb* -o -name .__afs* \) \) -print
ACLOCAL = ${SHELL} '/data/data/com.termux/files/home/sugarmaker/missing' aclocal-1.18
ALLOCA = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} '/data/data/com.termux/files/home/sugarmaker/missing' autoconf
AUTOHEADER = ${SHELL} '/data/data/com.termux/files/home/sugarmaker/missing' autoheader
AUTOMAKE = ${SHELL} '/data/data/com.termux/files/home/sugarmaker/missing' automake-1.18
AWK = gawk
CC = gcc
CCAS = gcc
CCASDEPMODE = depmode=gcc3
CCASFLAGS = -Wall -O2 -fomit-frame-pointer -I/data/data/com.termux/files/usr/include
CCDEPMODE = depmode=gcc3
CFLAGS = -Wall -O2 -fomit-frame-pointer -I/data/data/com.termux/files/usr/include 
CPPFLAGS =  
CSCOPE = cscope
CTAGS = ctags
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /data/data/com.termux/files/usr/bin/grep -E
ETAGS = etags
EXEEXT = 
GREP = /data/data/com.termux/files/usr/bin/grep
INSTALL = /data/data/com.termux/files/usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JANSSON_LIBS = -ljansson
LDFLAGS = -L/data/data/com.termux/files/usr/lib 
LIBCURL = -lcurl
LIBCURL_CPPFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAINT = #
MAKEINFO = ${SHELL} '/data/data/com.termux/files/home/sugarmaker/missing' makeinfo
MKDIR_P = /data/data/com.termux/files/usr/bin/mkdir -p
OBJEXT = o
PACKAGE = sugarmaker
PACKAGE_BUGREPORT = 
PACKAGE_NAME = sugarmaker
PACKAGE_STRING = sugarmaker 2.5.0-sugar4
PACKAGE_TARNAME = sugarmaker
PACKAGE_URL = 
PACKAGE_VERSION = 2.5.0-sugar4
PATH_SEPARATOR = :
PTHREAD_FLAGS = -pthread
PTHREAD_LIBS = -lpthread
RANLIB = :
SET_MAKE = 
SHELL = /data/data/com.termux/files/usr/bin/sh
STRIP = 
VERSION = 2.5.0-sugar4
WS2_LIBS = 
_libcurl_config = 
abs_builddir = /data/data/com.termux/files/home/sugarmaker
abs_srcdir = /data/data/com.termux/files/home/sugarmaker
abs_top_builddir = /data/data/com.termux/files/home/sugarmaker
abs_top_srcdir = /data/data/com.termux/files/home/sugarmaker
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__rm_f_notfound = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
am__xargs_n = xargs -n
bindir = ${exec_prefix}/bin
build = aarch64-unknown-linux-android
build_alias = 
build_cpu = aarch64
build_os = linux-android
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = aarch64-unknown-linux-android
host_alias = 
host_cpu = aarch64
host_os = linux-android
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /data/data/com.termux/files/home/sugarmaker/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /data/data/com.termux/files/usr
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = aarch64-unknown-linux-android
target_alias = 
target_cpu = aarch64
target_os = linux-android
target_vendor = unknown
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = subdir-objects
JANSSON_INCLUDES = 
#JANSSON_INCLUDES = -I$(top_srcdir)/compat/jansson
EXTRA_DIST = example-cfg.json
SUBDIRS = compat
dist_man_MANS = sugarmaker.1
sugarmaker_SOURCES = elist.h miner.h compat.h \
									cpu-miner.c util.c \
									sha2.c \
									yespower-1.0.1/sha256.c yespower-1.0.1/yespower-opt.c \
									YespowerSugar.c \
									YespowerIso.c \
									YespowerNull.c \
									YespowerUrx.c \
									YespowerLitb.c \
									YespowerIots.c \
									YespowerItc.c \
									yespower-1.0.1-power2b/sha256-p2b.c yespower-1.0.1-power2b/yespower-opt-p2b.c yespower-1.0.1-power2b/blake2b.c \
									YespowerMbc.c \
									YespowerYtn.c \
									YespowerAdvc.c

sugarmaker_LDFLAGS = $(PTHREAD_FLAGS)
sugarmaker_LDADD = -lcurl -ljansson -lpthread 
sugarmaker_CPPFLAGS = $(PTHREAD_FLAGS)   $(JANSSON_INCLUDES)
all: cpuminer-config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure: # $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

cpuminer-config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/cpuminer-config.h.in $(top_builddir)/config.status
	$(AM_V_at)rm -f stamp-h1
	$(AM_V_GEN)cd $(top_builddir) && $(SHELL) ./config.status cpuminer-config.h
$(srcdir)/cpuminer-config.h.in: # $(am__configure_deps) 
	$(AM_V_GEN)($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	$(AM_V_at)rm -f stamp-h1
	$(AM_V_at)touch $@

distclean-hdr:
	-rm -f cpuminer-config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && $(am__rm_f) $$files

clean-binPROGRAMS:
	-$(am__rm_f) $(bin_PROGRAMS)
yespower-1.0.1/$(am__dirstamp):
	@$(MKDIR_P) yespower-1.0.1
	@: >>yespower-1.0.1/$(am__dirstamp)
yespower-1.0.1/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) yespower-1.0.1/$(DEPDIR)
	@: >>yespower-1.0.1/$(DEPDIR)/$(am__dirstamp)
yespower-1.0.1/sugarmaker-sha256.$(OBJEXT):  \
	yespower-1.0.1/$(am__dirstamp) \
	yespower-1.0.1/$(DEPDIR)/$(am__dirstamp)
yespower-1.0.1/sugarmaker-yespower-opt.$(OBJEXT):  \
	yespower-1.0.1/$(am__dirstamp) \
	yespower-1.0.1/$(DEPDIR)/$(am__dirstamp)
yespower-1.0.1-power2b/$(am__dirstamp):
	@$(MKDIR_P) yespower-1.0.1-power2b
	@: >>yespower-1.0.1-power2b/$(am__dirstamp)
yespower-1.0.1-power2b/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) yespower-1.0.1-power2b/$(DEPDIR)
	@: >>yespower-1.0.1-power2b/$(DEPDIR)/$(am__dirstamp)
yespower-1.0.1-power2b/sugarmaker-sha256-p2b.$(OBJEXT):  \
	yespower-1.0.1-power2b/$(am__dirstamp) \
	yespower-1.0.1-power2b/$(DEPDIR)/$(am__dirstamp)
yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.$(OBJEXT):  \
	yespower-1.0.1-power2b/$(am__dirstamp) \
	yespower-1.0.1-power2b/$(DEPDIR)/$(am__dirstamp)
yespower-1.0.1-power2b/sugarmaker-blake2b.$(OBJEXT):  \
	yespower-1.0.1-power2b/$(am__dirstamp) \
	yespower-1.0.1-power2b/$(DEPDIR)/$(am__dirstamp)

sugarmaker$(EXEEXT): $(sugarmaker_OBJECTS) $(sugarmaker_DEPENDENCIES) $(EXTRA_sugarmaker_DEPENDENCIES) 
	@rm -f sugarmaker$(EXEEXT)
	$(AM_V_CCLD)$(sugarmaker_LINK) $(sugarmaker_OBJECTS) $(sugarmaker_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f yespower-1.0.1-power2b/*.$(OBJEXT)
	-rm -f yespower-1.0.1/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/sugarmaker-YespowerAdvc.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-YespowerIots.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-YespowerIso.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-YespowerItc.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-YespowerLitb.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-YespowerMbc.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-YespowerNull.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-YespowerSugar.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-YespowerUrx.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-YespowerYtn.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-cpu-miner.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-sha2.Po # am--include-marker
include ./$(DEPDIR)/sugarmaker-util.Po # am--include-marker
include yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-blake2b.Po # am--include-marker
include yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-sha256-p2b.Po # am--include-marker
include yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-yespower-opt-p2b.Po # am--include-marker
include yespower-1.0.1/$(DEPDIR)/sugarmaker-sha256.Po # am--include-marker
include yespower-1.0.1/$(DEPDIR)/sugarmaker-yespower-opt.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@: >>$@

am--depfiles: $(am__depfiles_remade)

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

sugarmaker-cpu-miner.o: cpu-miner.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-cpu-miner.o -MD -MP -MF $(DEPDIR)/sugarmaker-cpu-miner.Tpo -c -o sugarmaker-cpu-miner.o `test -f 'cpu-miner.c' || echo '$(srcdir)/'`cpu-miner.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-cpu-miner.Tpo $(DEPDIR)/sugarmaker-cpu-miner.Po
#	$(AM_V_CC)source='cpu-miner.c' object='sugarmaker-cpu-miner.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-cpu-miner.o `test -f 'cpu-miner.c' || echo '$(srcdir)/'`cpu-miner.c

sugarmaker-cpu-miner.obj: cpu-miner.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-cpu-miner.obj -MD -MP -MF $(DEPDIR)/sugarmaker-cpu-miner.Tpo -c -o sugarmaker-cpu-miner.obj `if test -f 'cpu-miner.c'; then $(CYGPATH_W) 'cpu-miner.c'; else $(CYGPATH_W) '$(srcdir)/cpu-miner.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-cpu-miner.Tpo $(DEPDIR)/sugarmaker-cpu-miner.Po
#	$(AM_V_CC)source='cpu-miner.c' object='sugarmaker-cpu-miner.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-cpu-miner.obj `if test -f 'cpu-miner.c'; then $(CYGPATH_W) 'cpu-miner.c'; else $(CYGPATH_W) '$(srcdir)/cpu-miner.c'; fi`

sugarmaker-util.o: util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-util.o -MD -MP -MF $(DEPDIR)/sugarmaker-util.Tpo -c -o sugarmaker-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-util.Tpo $(DEPDIR)/sugarmaker-util.Po
#	$(AM_V_CC)source='util.c' object='sugarmaker-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c

sugarmaker-util.obj: util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-util.obj -MD -MP -MF $(DEPDIR)/sugarmaker-util.Tpo -c -o sugarmaker-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-util.Tpo $(DEPDIR)/sugarmaker-util.Po
#	$(AM_V_CC)source='util.c' object='sugarmaker-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`

sugarmaker-sha2.o: sha2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-sha2.o -MD -MP -MF $(DEPDIR)/sugarmaker-sha2.Tpo -c -o sugarmaker-sha2.o `test -f 'sha2.c' || echo '$(srcdir)/'`sha2.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-sha2.Tpo $(DEPDIR)/sugarmaker-sha2.Po
#	$(AM_V_CC)source='sha2.c' object='sugarmaker-sha2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-sha2.o `test -f 'sha2.c' || echo '$(srcdir)/'`sha2.c

sugarmaker-sha2.obj: sha2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-sha2.obj -MD -MP -MF $(DEPDIR)/sugarmaker-sha2.Tpo -c -o sugarmaker-sha2.obj `if test -f 'sha2.c'; then $(CYGPATH_W) 'sha2.c'; else $(CYGPATH_W) '$(srcdir)/sha2.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-sha2.Tpo $(DEPDIR)/sugarmaker-sha2.Po
#	$(AM_V_CC)source='sha2.c' object='sugarmaker-sha2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-sha2.obj `if test -f 'sha2.c'; then $(CYGPATH_W) 'sha2.c'; else $(CYGPATH_W) '$(srcdir)/sha2.c'; fi`

yespower-1.0.1/sugarmaker-sha256.o: yespower-1.0.1/sha256.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT yespower-1.0.1/sugarmaker-sha256.o -MD -MP -MF yespower-1.0.1/$(DEPDIR)/sugarmaker-sha256.Tpo -c -o yespower-1.0.1/sugarmaker-sha256.o `test -f 'yespower-1.0.1/sha256.c' || echo '$(srcdir)/'`yespower-1.0.1/sha256.c
	$(AM_V_at)$(am__mv) yespower-1.0.1/$(DEPDIR)/sugarmaker-sha256.Tpo yespower-1.0.1/$(DEPDIR)/sugarmaker-sha256.Po
#	$(AM_V_CC)source='yespower-1.0.1/sha256.c' object='yespower-1.0.1/sugarmaker-sha256.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o yespower-1.0.1/sugarmaker-sha256.o `test -f 'yespower-1.0.1/sha256.c' || echo '$(srcdir)/'`yespower-1.0.1/sha256.c

yespower-1.0.1/sugarmaker-sha256.obj: yespower-1.0.1/sha256.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT yespower-1.0.1/sugarmaker-sha256.obj -MD -MP -MF yespower-1.0.1/$(DEPDIR)/sugarmaker-sha256.Tpo -c -o yespower-1.0.1/sugarmaker-sha256.obj `if test -f 'yespower-1.0.1/sha256.c'; then $(CYGPATH_W) 'yespower-1.0.1/sha256.c'; else $(CYGPATH_W) '$(srcdir)/yespower-1.0.1/sha256.c'; fi`
	$(AM_V_at)$(am__mv) yespower-1.0.1/$(DEPDIR)/sugarmaker-sha256.Tpo yespower-1.0.1/$(DEPDIR)/sugarmaker-sha256.Po
#	$(AM_V_CC)source='yespower-1.0.1/sha256.c' object='yespower-1.0.1/sugarmaker-sha256.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o yespower-1.0.1/sugarmaker-sha256.obj `if test -f 'yespower-1.0.1/sha256.c'; then $(CYGPATH_W) 'yespower-1.0.1/sha256.c'; else $(CYGPATH_W) '$(srcdir)/yespower-1.0.1/sha256.c'; fi`

yespower-1.0.1/sugarmaker-yespower-opt.o: yespower-1.0.1/yespower-opt.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT yespower-1.0.1/sugarmaker-yespower-opt.o -MD -MP -MF yespower-1.0.1/$(DEPDIR)/sugarmaker-yespower-opt.Tpo -c -o yespower-1.0.1/sugarmaker-yespower-opt.o `test -f 'yespower-1.0.1/yespower-opt.c' || echo '$(srcdir)/'`yespower-1.0.1/yespower-opt.c
	$(AM_V_at)$(am__mv) yespower-1.0.1/$(DEPDIR)/sugarmaker-yespower-opt.Tpo yespower-1.0.1/$(DEPDIR)/sugarmaker-yespower-opt.Po
#	$(AM_V_CC)source='yespower-1.0.1/yespower-opt.c' object='yespower-1.0.1/sugarmaker-yespower-opt.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o yespower-1.0.1/sugarmaker-yespower-opt.o `test -f 'yespower-1.0.1/yespower-opt.c' || echo '$(srcdir)/'`yespower-1.0.1/yespower-opt.c

yespower-1.0.1/sugarmaker-yespower-opt.obj: yespower-1.0.1/yespower-opt.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT yespower-1.0.1/sugarmaker-yespower-opt.obj -MD -MP -MF yespower-1.0.1/$(DEPDIR)/sugarmaker-yespower-opt.Tpo -c -o yespower-1.0.1/sugarmaker-yespower-opt.obj `if test -f 'yespower-1.0.1/yespower-opt.c'; then $(CYGPATH_W) 'yespower-1.0.1/yespower-opt.c'; else $(CYGPATH_W) '$(srcdir)/yespower-1.0.1/yespower-opt.c'; fi`
	$(AM_V_at)$(am__mv) yespower-1.0.1/$(DEPDIR)/sugarmaker-yespower-opt.Tpo yespower-1.0.1/$(DEPDIR)/sugarmaker-yespower-opt.Po
#	$(AM_V_CC)source='yespower-1.0.1/yespower-opt.c' object='yespower-1.0.1/sugarmaker-yespower-opt.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o yespower-1.0.1/sugarmaker-yespower-opt.obj `if test -f 'yespower-1.0.1/yespower-opt.c'; then $(CYGPATH_W) 'yespower-1.0.1/yespower-opt.c'; else $(CYGPATH_W) '$(srcdir)/yespower-1.0.1/yespower-opt.c'; fi`

sugarmaker-YespowerSugar.o: YespowerSugar.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerSugar.o -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerSugar.Tpo -c -o sugarmaker-YespowerSugar.o `test -f 'YespowerSugar.c' || echo '$(srcdir)/'`YespowerSugar.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerSugar.Tpo $(DEPDIR)/sugarmaker-YespowerSugar.Po
#	$(AM_V_CC)source='YespowerSugar.c' object='sugarmaker-YespowerSugar.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerSugar.o `test -f 'YespowerSugar.c' || echo '$(srcdir)/'`YespowerSugar.c

sugarmaker-YespowerSugar.obj: YespowerSugar.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerSugar.obj -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerSugar.Tpo -c -o sugarmaker-YespowerSugar.obj `if test -f 'YespowerSugar.c'; then $(CYGPATH_W) 'YespowerSugar.c'; else $(CYGPATH_W) '$(srcdir)/YespowerSugar.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerSugar.Tpo $(DEPDIR)/sugarmaker-YespowerSugar.Po
#	$(AM_V_CC)source='YespowerSugar.c' object='sugarmaker-YespowerSugar.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerSugar.obj `if test -f 'YespowerSugar.c'; then $(CYGPATH_W) 'YespowerSugar.c'; else $(CYGPATH_W) '$(srcdir)/YespowerSugar.c'; fi`

sugarmaker-YespowerIso.o: YespowerIso.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerIso.o -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerIso.Tpo -c -o sugarmaker-YespowerIso.o `test -f 'YespowerIso.c' || echo '$(srcdir)/'`YespowerIso.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerIso.Tpo $(DEPDIR)/sugarmaker-YespowerIso.Po
#	$(AM_V_CC)source='YespowerIso.c' object='sugarmaker-YespowerIso.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerIso.o `test -f 'YespowerIso.c' || echo '$(srcdir)/'`YespowerIso.c

sugarmaker-YespowerIso.obj: YespowerIso.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerIso.obj -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerIso.Tpo -c -o sugarmaker-YespowerIso.obj `if test -f 'YespowerIso.c'; then $(CYGPATH_W) 'YespowerIso.c'; else $(CYGPATH_W) '$(srcdir)/YespowerIso.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerIso.Tpo $(DEPDIR)/sugarmaker-YespowerIso.Po
#	$(AM_V_CC)source='YespowerIso.c' object='sugarmaker-YespowerIso.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerIso.obj `if test -f 'YespowerIso.c'; then $(CYGPATH_W) 'YespowerIso.c'; else $(CYGPATH_W) '$(srcdir)/YespowerIso.c'; fi`

sugarmaker-YespowerNull.o: YespowerNull.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerNull.o -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerNull.Tpo -c -o sugarmaker-YespowerNull.o `test -f 'YespowerNull.c' || echo '$(srcdir)/'`YespowerNull.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerNull.Tpo $(DEPDIR)/sugarmaker-YespowerNull.Po
#	$(AM_V_CC)source='YespowerNull.c' object='sugarmaker-YespowerNull.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerNull.o `test -f 'YespowerNull.c' || echo '$(srcdir)/'`YespowerNull.c

sugarmaker-YespowerNull.obj: YespowerNull.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerNull.obj -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerNull.Tpo -c -o sugarmaker-YespowerNull.obj `if test -f 'YespowerNull.c'; then $(CYGPATH_W) 'YespowerNull.c'; else $(CYGPATH_W) '$(srcdir)/YespowerNull.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerNull.Tpo $(DEPDIR)/sugarmaker-YespowerNull.Po
#	$(AM_V_CC)source='YespowerNull.c' object='sugarmaker-YespowerNull.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerNull.obj `if test -f 'YespowerNull.c'; then $(CYGPATH_W) 'YespowerNull.c'; else $(CYGPATH_W) '$(srcdir)/YespowerNull.c'; fi`

sugarmaker-YespowerUrx.o: YespowerUrx.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerUrx.o -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerUrx.Tpo -c -o sugarmaker-YespowerUrx.o `test -f 'YespowerUrx.c' || echo '$(srcdir)/'`YespowerUrx.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerUrx.Tpo $(DEPDIR)/sugarmaker-YespowerUrx.Po
#	$(AM_V_CC)source='YespowerUrx.c' object='sugarmaker-YespowerUrx.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerUrx.o `test -f 'YespowerUrx.c' || echo '$(srcdir)/'`YespowerUrx.c

sugarmaker-YespowerUrx.obj: YespowerUrx.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerUrx.obj -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerUrx.Tpo -c -o sugarmaker-YespowerUrx.obj `if test -f 'YespowerUrx.c'; then $(CYGPATH_W) 'YespowerUrx.c'; else $(CYGPATH_W) '$(srcdir)/YespowerUrx.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerUrx.Tpo $(DEPDIR)/sugarmaker-YespowerUrx.Po
#	$(AM_V_CC)source='YespowerUrx.c' object='sugarmaker-YespowerUrx.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerUrx.obj `if test -f 'YespowerUrx.c'; then $(CYGPATH_W) 'YespowerUrx.c'; else $(CYGPATH_W) '$(srcdir)/YespowerUrx.c'; fi`

sugarmaker-YespowerLitb.o: YespowerLitb.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerLitb.o -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerLitb.Tpo -c -o sugarmaker-YespowerLitb.o `test -f 'YespowerLitb.c' || echo '$(srcdir)/'`YespowerLitb.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerLitb.Tpo $(DEPDIR)/sugarmaker-YespowerLitb.Po
#	$(AM_V_CC)source='YespowerLitb.c' object='sugarmaker-YespowerLitb.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerLitb.o `test -f 'YespowerLitb.c' || echo '$(srcdir)/'`YespowerLitb.c

sugarmaker-YespowerLitb.obj: YespowerLitb.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerLitb.obj -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerLitb.Tpo -c -o sugarmaker-YespowerLitb.obj `if test -f 'YespowerLitb.c'; then $(CYGPATH_W) 'YespowerLitb.c'; else $(CYGPATH_W) '$(srcdir)/YespowerLitb.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerLitb.Tpo $(DEPDIR)/sugarmaker-YespowerLitb.Po
#	$(AM_V_CC)source='YespowerLitb.c' object='sugarmaker-YespowerLitb.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerLitb.obj `if test -f 'YespowerLitb.c'; then $(CYGPATH_W) 'YespowerLitb.c'; else $(CYGPATH_W) '$(srcdir)/YespowerLitb.c'; fi`

sugarmaker-YespowerIots.o: YespowerIots.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerIots.o -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerIots.Tpo -c -o sugarmaker-YespowerIots.o `test -f 'YespowerIots.c' || echo '$(srcdir)/'`YespowerIots.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerIots.Tpo $(DEPDIR)/sugarmaker-YespowerIots.Po
#	$(AM_V_CC)source='YespowerIots.c' object='sugarmaker-YespowerIots.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerIots.o `test -f 'YespowerIots.c' || echo '$(srcdir)/'`YespowerIots.c

sugarmaker-YespowerIots.obj: YespowerIots.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerIots.obj -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerIots.Tpo -c -o sugarmaker-YespowerIots.obj `if test -f 'YespowerIots.c'; then $(CYGPATH_W) 'YespowerIots.c'; else $(CYGPATH_W) '$(srcdir)/YespowerIots.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerIots.Tpo $(DEPDIR)/sugarmaker-YespowerIots.Po
#	$(AM_V_CC)source='YespowerIots.c' object='sugarmaker-YespowerIots.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerIots.obj `if test -f 'YespowerIots.c'; then $(CYGPATH_W) 'YespowerIots.c'; else $(CYGPATH_W) '$(srcdir)/YespowerIots.c'; fi`

sugarmaker-YespowerItc.o: YespowerItc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerItc.o -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerItc.Tpo -c -o sugarmaker-YespowerItc.o `test -f 'YespowerItc.c' || echo '$(srcdir)/'`YespowerItc.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerItc.Tpo $(DEPDIR)/sugarmaker-YespowerItc.Po
#	$(AM_V_CC)source='YespowerItc.c' object='sugarmaker-YespowerItc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerItc.o `test -f 'YespowerItc.c' || echo '$(srcdir)/'`YespowerItc.c

sugarmaker-YespowerItc.obj: YespowerItc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerItc.obj -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerItc.Tpo -c -o sugarmaker-YespowerItc.obj `if test -f 'YespowerItc.c'; then $(CYGPATH_W) 'YespowerItc.c'; else $(CYGPATH_W) '$(srcdir)/YespowerItc.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerItc.Tpo $(DEPDIR)/sugarmaker-YespowerItc.Po
#	$(AM_V_CC)source='YespowerItc.c' object='sugarmaker-YespowerItc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerItc.obj `if test -f 'YespowerItc.c'; then $(CYGPATH_W) 'YespowerItc.c'; else $(CYGPATH_W) '$(srcdir)/YespowerItc.c'; fi`

yespower-1.0.1-power2b/sugarmaker-sha256-p2b.o: yespower-1.0.1-power2b/sha256-p2b.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT yespower-1.0.1-power2b/sugarmaker-sha256-p2b.o -MD -MP -MF yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-sha256-p2b.Tpo -c -o yespower-1.0.1-power2b/sugarmaker-sha256-p2b.o `test -f 'yespower-1.0.1-power2b/sha256-p2b.c' || echo '$(srcdir)/'`yespower-1.0.1-power2b/sha256-p2b.c
	$(AM_V_at)$(am__mv) yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-sha256-p2b.Tpo yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-sha256-p2b.Po
#	$(AM_V_CC)source='yespower-1.0.1-power2b/sha256-p2b.c' object='yespower-1.0.1-power2b/sugarmaker-sha256-p2b.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o yespower-1.0.1-power2b/sugarmaker-sha256-p2b.o `test -f 'yespower-1.0.1-power2b/sha256-p2b.c' || echo '$(srcdir)/'`yespower-1.0.1-power2b/sha256-p2b.c

yespower-1.0.1-power2b/sugarmaker-sha256-p2b.obj: yespower-1.0.1-power2b/sha256-p2b.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT yespower-1.0.1-power2b/sugarmaker-sha256-p2b.obj -MD -MP -MF yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-sha256-p2b.Tpo -c -o yespower-1.0.1-power2b/sugarmaker-sha256-p2b.obj `if test -f 'yespower-1.0.1-power2b/sha256-p2b.c'; then $(CYGPATH_W) 'yespower-1.0.1-power2b/sha256-p2b.c'; else $(CYGPATH_W) '$(srcdir)/yespower-1.0.1-power2b/sha256-p2b.c'; fi`
	$(AM_V_at)$(am__mv) yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-sha256-p2b.Tpo yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-sha256-p2b.Po
#	$(AM_V_CC)source='yespower-1.0.1-power2b/sha256-p2b.c' object='yespower-1.0.1-power2b/sugarmaker-sha256-p2b.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o yespower-1.0.1-power2b/sugarmaker-sha256-p2b.obj `if test -f 'yespower-1.0.1-power2b/sha256-p2b.c'; then $(CYGPATH_W) 'yespower-1.0.1-power2b/sha256-p2b.c'; else $(CYGPATH_W) '$(srcdir)/yespower-1.0.1-power2b/sha256-p2b.c'; fi`

yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.o: yespower-1.0.1-power2b/yespower-opt-p2b.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.o -MD -MP -MF yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-yespower-opt-p2b.Tpo -c -o yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.o `test -f 'yespower-1.0.1-power2b/yespower-opt-p2b.c' || echo '$(srcdir)/'`yespower-1.0.1-power2b/yespower-opt-p2b.c
	$(AM_V_at)$(am__mv) yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-yespower-opt-p2b.Tpo yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-yespower-opt-p2b.Po
#	$(AM_V_CC)source='yespower-1.0.1-power2b/yespower-opt-p2b.c' object='yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.o `test -f 'yespower-1.0.1-power2b/yespower-opt-p2b.c' || echo '$(srcdir)/'`yespower-1.0.1-power2b/yespower-opt-p2b.c

yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.obj: yespower-1.0.1-power2b/yespower-opt-p2b.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.obj -MD -MP -MF yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-yespower-opt-p2b.Tpo -c -o yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.obj `if test -f 'yespower-1.0.1-power2b/yespower-opt-p2b.c'; then $(CYGPATH_W) 'yespower-1.0.1-power2b/yespower-opt-p2b.c'; else $(CYGPATH_W) '$(srcdir)/yespower-1.0.1-power2b/yespower-opt-p2b.c'; fi`
	$(AM_V_at)$(am__mv) yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-yespower-opt-p2b.Tpo yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-yespower-opt-p2b.Po
#	$(AM_V_CC)source='yespower-1.0.1-power2b/yespower-opt-p2b.c' object='yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o yespower-1.0.1-power2b/sugarmaker-yespower-opt-p2b.obj `if test -f 'yespower-1.0.1-power2b/yespower-opt-p2b.c'; then $(CYGPATH_W) 'yespower-1.0.1-power2b/yespower-opt-p2b.c'; else $(CYGPATH_W) '$(srcdir)/yespower-1.0.1-power2b/yespower-opt-p2b.c'; fi`

yespower-1.0.1-power2b/sugarmaker-blake2b.o: yespower-1.0.1-power2b/blake2b.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT yespower-1.0.1-power2b/sugarmaker-blake2b.o -MD -MP -MF yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-blake2b.Tpo -c -o yespower-1.0.1-power2b/sugarmaker-blake2b.o `test -f 'yespower-1.0.1-power2b/blake2b.c' || echo '$(srcdir)/'`yespower-1.0.1-power2b/blake2b.c
	$(AM_V_at)$(am__mv) yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-blake2b.Tpo yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-blake2b.Po
#	$(AM_V_CC)source='yespower-1.0.1-power2b/blake2b.c' object='yespower-1.0.1-power2b/sugarmaker-blake2b.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o yespower-1.0.1-power2b/sugarmaker-blake2b.o `test -f 'yespower-1.0.1-power2b/blake2b.c' || echo '$(srcdir)/'`yespower-1.0.1-power2b/blake2b.c

yespower-1.0.1-power2b/sugarmaker-blake2b.obj: yespower-1.0.1-power2b/blake2b.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT yespower-1.0.1-power2b/sugarmaker-blake2b.obj -MD -MP -MF yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-blake2b.Tpo -c -o yespower-1.0.1-power2b/sugarmaker-blake2b.obj `if test -f 'yespower-1.0.1-power2b/blake2b.c'; then $(CYGPATH_W) 'yespower-1.0.1-power2b/blake2b.c'; else $(CYGPATH_W) '$(srcdir)/yespower-1.0.1-power2b/blake2b.c'; fi`
	$(AM_V_at)$(am__mv) yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-blake2b.Tpo yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-blake2b.Po
#	$(AM_V_CC)source='yespower-1.0.1-power2b/blake2b.c' object='yespower-1.0.1-power2b/sugarmaker-blake2b.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o yespower-1.0.1-power2b/sugarmaker-blake2b.obj `if test -f 'yespower-1.0.1-power2b/blake2b.c'; then $(CYGPATH_W) 'yespower-1.0.1-power2b/blake2b.c'; else $(CYGPATH_W) '$(srcdir)/yespower-1.0.1-power2b/blake2b.c'; fi`

sugarmaker-YespowerMbc.o: YespowerMbc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerMbc.o -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerMbc.Tpo -c -o sugarmaker-YespowerMbc.o `test -f 'YespowerMbc.c' || echo '$(srcdir)/'`YespowerMbc.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerMbc.Tpo $(DEPDIR)/sugarmaker-YespowerMbc.Po
#	$(AM_V_CC)source='YespowerMbc.c' object='sugarmaker-YespowerMbc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerMbc.o `test -f 'YespowerMbc.c' || echo '$(srcdir)/'`YespowerMbc.c

sugarmaker-YespowerMbc.obj: YespowerMbc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerMbc.obj -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerMbc.Tpo -c -o sugarmaker-YespowerMbc.obj `if test -f 'YespowerMbc.c'; then $(CYGPATH_W) 'YespowerMbc.c'; else $(CYGPATH_W) '$(srcdir)/YespowerMbc.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerMbc.Tpo $(DEPDIR)/sugarmaker-YespowerMbc.Po
#	$(AM_V_CC)source='YespowerMbc.c' object='sugarmaker-YespowerMbc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerMbc.obj `if test -f 'YespowerMbc.c'; then $(CYGPATH_W) 'YespowerMbc.c'; else $(CYGPATH_W) '$(srcdir)/YespowerMbc.c'; fi`

sugarmaker-YespowerYtn.o: YespowerYtn.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerYtn.o -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerYtn.Tpo -c -o sugarmaker-YespowerYtn.o `test -f 'YespowerYtn.c' || echo '$(srcdir)/'`YespowerYtn.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerYtn.Tpo $(DEPDIR)/sugarmaker-YespowerYtn.Po
#	$(AM_V_CC)source='YespowerYtn.c' object='sugarmaker-YespowerYtn.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerYtn.o `test -f 'YespowerYtn.c' || echo '$(srcdir)/'`YespowerYtn.c

sugarmaker-YespowerYtn.obj: YespowerYtn.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerYtn.obj -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerYtn.Tpo -c -o sugarmaker-YespowerYtn.obj `if test -f 'YespowerYtn.c'; then $(CYGPATH_W) 'YespowerYtn.c'; else $(CYGPATH_W) '$(srcdir)/YespowerYtn.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerYtn.Tpo $(DEPDIR)/sugarmaker-YespowerYtn.Po
#	$(AM_V_CC)source='YespowerYtn.c' object='sugarmaker-YespowerYtn.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerYtn.obj `if test -f 'YespowerYtn.c'; then $(CYGPATH_W) 'YespowerYtn.c'; else $(CYGPATH_W) '$(srcdir)/YespowerYtn.c'; fi`

sugarmaker-YespowerAdvc.o: YespowerAdvc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerAdvc.o -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerAdvc.Tpo -c -o sugarmaker-YespowerAdvc.o `test -f 'YespowerAdvc.c' || echo '$(srcdir)/'`YespowerAdvc.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerAdvc.Tpo $(DEPDIR)/sugarmaker-YespowerAdvc.Po
#	$(AM_V_CC)source='YespowerAdvc.c' object='sugarmaker-YespowerAdvc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerAdvc.o `test -f 'YespowerAdvc.c' || echo '$(srcdir)/'`YespowerAdvc.c

sugarmaker-YespowerAdvc.obj: YespowerAdvc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sugarmaker-YespowerAdvc.obj -MD -MP -MF $(DEPDIR)/sugarmaker-YespowerAdvc.Tpo -c -o sugarmaker-YespowerAdvc.obj `if test -f 'YespowerAdvc.c'; then $(CYGPATH_W) 'YespowerAdvc.c'; else $(CYGPATH_W) '$(srcdir)/YespowerAdvc.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sugarmaker-YespowerAdvc.Tpo $(DEPDIR)/sugarmaker-YespowerAdvc.Po
#	$(AM_V_CC)source='YespowerAdvc.c' object='sugarmaker-YespowerAdvc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sugarmaker_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sugarmaker-YespowerAdvc.obj `if test -f 'YespowerAdvc.c'; then $(CYGPATH_W) 'YespowerAdvc.c'; else $(CYGPATH_W) '$(srcdir)/YespowerAdvc.c'; fi`
install-man1: $(dist_man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(dist_man_MANS)'; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.1[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	$(AM_V_at)$(MKDIR_P) "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-bzip3: distdir
	tardir=$(distdir) && $(am__tar) | bzip3 -c >$(distdir).tar.bz3
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-zstd: distdir
	tardir=$(distdir) && $(am__tar) | zstd -c $${ZSTD_CLEVEL-$${ZSTD_OPT--19}} >$(distdir).tar.zst
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.bz3*) \
	  bzip3 -dc $(distdir).tar.bz3 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	*.tar.zst*) \
	  zstd -dc $(distdir).tar.zst | $(am__untar) ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) $(AM_DISTCHECK_DVI_TARGET) \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS) $(MANS) cpuminer-config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-$(am__rm_f) $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || $(am__rm_f) $(CONFIG_CLEAN_VPATH_FILES)
	-$(am__rm_f) yespower-1.0.1-power2b/$(DEPDIR)/$(am__dirstamp)
	-$(am__rm_f) yespower-1.0.1-power2b/$(am__dirstamp)
	-$(am__rm_f) yespower-1.0.1/$(DEPDIR)/$(am__dirstamp)
	-$(am__rm_f) yespower-1.0.1/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerAdvc.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerIots.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerIso.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerItc.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerLitb.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerMbc.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerNull.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerSugar.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerUrx.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerYtn.Po
	-rm -f ./$(DEPDIR)/sugarmaker-cpu-miner.Po
	-rm -f ./$(DEPDIR)/sugarmaker-sha2.Po
	-rm -f ./$(DEPDIR)/sugarmaker-util.Po
	-rm -f yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-blake2b.Po
	-rm -f yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-sha256-p2b.Po
	-rm -f yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-yespower-opt-p2b.Po
	-rm -f yespower-1.0.1/$(DEPDIR)/sugarmaker-sha256.Po
	-rm -f yespower-1.0.1/$(DEPDIR)/sugarmaker-yespower-opt.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-man

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man: install-man1

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerAdvc.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerIots.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerIso.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerItc.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerLitb.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerMbc.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerNull.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerSugar.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerUrx.Po
	-rm -f ./$(DEPDIR)/sugarmaker-YespowerYtn.Po
	-rm -f ./$(DEPDIR)/sugarmaker-cpu-miner.Po
	-rm -f ./$(DEPDIR)/sugarmaker-sha2.Po
	-rm -f ./$(DEPDIR)/sugarmaker-util.Po
	-rm -f yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-blake2b.Po
	-rm -f yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-sha256-p2b.Po
	-rm -f yespower-1.0.1-power2b/$(DEPDIR)/sugarmaker-yespower-opt-p2b.Po
	-rm -f yespower-1.0.1/$(DEPDIR)/sugarmaker-sha256.Po
	-rm -f yespower-1.0.1/$(DEPDIR)/sugarmaker-yespower-opt.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-man

uninstall-man: uninstall-man1

.MAKE: $(am__recursive_targets) all install-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--depfiles am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-bzip3 dist-gzip dist-lzip dist-shar dist-tarZ dist-xz \
	dist-zip dist-zstd distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-man1 install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs installdirs-am \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-man uninstall-man1

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

# Tell GNU make to disable its built-in pattern rules.
%:: %,v
%:: RCS/%,v
%:: RCS/%
%:: s.%
%:: SCCS/s.%
