/* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
#define CFLAGS cflags
/*
 * Generate CFLAGS as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char cflags[] = {
    'c','o','m','p','i','l','e','r',':',' ','c','c',' ','-','D','N',
    'D','E','B','U','G',' ','-','D','O','P','E','N','S','S','L','_',
    'N','O','_','D','Y','N','A','M','I','C','_','E','N','G','I','N',
    'E',' ','-','D','O','P','E','N','S','S','L','D','I','R','=','"',
    '\\','"','/','u','s','r','/','l','o','c','a','l','/','s','s','l',
    '\\','"','"',' ','-','D','E','N','G','I','N','E','S','D','I','R',
    '=','"','\\','"','/','u','s','r','/','l','o','c','a','l','/','l',
    'i','b','/','e','n','g','i','n','e','s','-','1','.','1','\\','"',
    '"',' ','\0'
};
#define PLATFORM "platform: dist"
#define DATE "built on: Tue Oct 14 08:15:42 2025"
